metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 192.168.10.64, gateway: 192.168.10.1, mac: '6c:2b:59:64:e6:66', disk: sda, network_interface: enp1s0}
    workers:
      hosts:
